# These are supported funding model platforms

github: [YuzakiKokuban]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  - https://www.paypal.me/LangQin280
  - https://qr.alipay.com/fkx13433fi3skccvxkldn48
